spring:
  datasource:
    url: jdbc:postgresql://192.168.33.10/springbootdbflute
    driver-class-name: org.postgresql.Driver
    username: springbootdbflute
    password: springbootdbflute
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  thymeleaf:
    cache: false